//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Trabalho_DA1.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}

/* 
 
cb_delete.Items.Insert(idProd -1, idProd.ToString());


 int position = cb_delete.SelectedIndex +1;
            for (int i = position - 1; i < idProd-1; i++)
            {
                produtos[i] = produtos[i + 1];
            }

            cb_delete.Items.Clear();
            cb_delete.ResetText();
            cb_id_produto.Items.Clear();
            cb_id_produto.ResetText();
            cb_id_produto_distribuidor.Items.Clear();
            cb_id_produto_distribuidor.ResetText();
            cb_id_prod_edit.Items.Clear();
            cb_id_prod_edit.ResetText();
            LimparLabel();
            for (int i = 0; i< idProd-1; i++)
            {
                cb_delete.Items.Insert(i, produtos[i].IdProduto);
                cb_id_produto.Items.Insert(i, produtos[i].IdProduto);
                cb_id_produto_distribuidor.Items.Insert(i, produtos[i].IdProduto);
                cb_id_prod_edit.Items.Insert(i, produtos[i].IdProduto);
            }
            idProd--;
 */